import { LegalLayout } from "@/components/layout/LegalLayout";

export default function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer">
      <p>Last updated: {new Date().toLocaleDateString()}</p>
      
      <h2>1. General Information</h2>
      <p>The information and code generated by Drasa AI is for general informational and development purposes only. While we strive for accuracy, the AI is a machine learning model and may produce errors, hallucinations, or suboptimal code.</p>

      <h2>2. No Professional Advice</h2>
      <p>Drasa AI does not provide professional, legal, or financial advice. Any code or configuration generated for production systems should be thoroughly reviewed by a qualified human engineer before deployment.</p>

      <h2>3. Liability</h2>
      <p>We make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the service. Any reliance you place on such information is therefore strictly at your own risk.</p>
    </LegalLayout>
  );
}
